"""Tabela Veículo

Revision ID: 255fb8ada417
Revises: 8b28e120bcdd
Create Date: 2024-10-23 02:05:10.689051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '255fb8ada417'
down_revision: Union[str, None] = '8b28e120bcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=False),
    sa.Column('cor', sa.String(), nullable=False),
    sa.Column('ano_fabricacao', sa.Integer(), nullable=False),
    sa.Column('ano_modelo', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(), nullable=False),
    sa.Column('placa', sa.String(), nullable=False),
    sa.Column('vendido', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    # ### end Alembic commands ###
