"""Add Veiculo table

Revision ID: 8b28e120bcdd
Revises: 1f85d161f1dd
Create Date: 2024-10-17 12:39:26.525875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b28e120bcdd'
down_revision: Union[str, None] = '1f85d161f1dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veiculo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('montadora_id', sa.UUID(), nullable=False),
    sa.Column('valor_referencia', sa.Numeric(), nullable=False),
    sa.Column('motorizacao', sa.Numeric(), nullable=False),
    sa.Column('turbo', sa.Boolean(), nullable=True),
    sa.Column('automatico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['montadora_id'], ['montadora.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('veiculo')
    # ### end Alembic commands ###
